apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: default
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.4'
    testBoolean: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    resources:
      requests:
        cpu: 0.5
        memory: 1Mi
    resourcesYaml:
      requests:
        cpu: 0.5
        memory: 1Mi
      limits:
        cpu: 0.5
        memory: 1Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}
